#!/bin/sh

# Deteksi lingkungan (Termux atau Linux)
if [ -d "/data/data/com.termux/files/usr" ] || [ -n "$PREFIX" ] && echo "$PREFIX" | grep -q "com.termux"; then
    # Termux environment
    PYTHON_SCRIPT="/data/data/com.termux/files/usr/bin//mulai.py"
    PYTHON_CMD="python"
else
    # Linux environment
    PYTHON_SCRIPT="/usr/bin/mulai.py"
    PYTHON_CMD="python3"
fi

# Periksa apakah file script Python ada
if [ -f "$PYTHON_SCRIPT" ]; then
    # Jalankan script Python
    exec "$PYTHON_CMD" "$PYTHON_SCRIPT"
else
    echo "Error: File $PYTHON_SCRIPT tidak ditemukan."
    exit 1
fi
